import { PropsWithChildren, useEffect, useState } from 'react'
import Head from 'next/head'
import clsx from 'clsx'
import { Inter } from '@next/font/google'
import { useAtom } from 'jotai'
import { themeAtom } from 'store'
import { motion } from 'framer-motion'
import Cursor from './Cursor'

const inter = Inter({ subsets: ['latin'] })

const Layout = ({ children }: PropsWithChildren) => {
  const [theme, setTheme] = useAtom(themeAtom)
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    document.body.classList.remove('light', 'dark')
    document.body.classList.add(theme)
  }, [theme])

  useEffect(() => {
    console.log(
      '\n',
      'Hello there!',
      '\n',
      'Want to reach out?!',
      '\n',
      'Shoot me an email @',
      '\n',
      'soreilly424@gmail.com',
      '\n',
      '🤗'
    )
    setMounted(true)
  }, [])

  return (
    <motion.div
      animate={{
        backgroundColor: theme === 'dark' ? 'var(--dark)' : 'var(--light)',
      }}
      className={clsx(
        'flex min-h-screen flex-col transition-all duration-100 ease-linear',
        inter.className
      )}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {mounted && <Cursor />}
      <main className="container py-10">
        <button
          className="button my-4 w-max"
          onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
        >
          toggle theme
        </button>
        {children}
      </main>
      <footer className="mt-auto flex justify-center gap-3">
        <p>hello</p>
        <p>hello</p>
        <p>hello</p>
        <p>hello</p>
      </footer>
    </motion.div>
  )
}

export default Layout
