import clsx from 'clsx'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { getSortedPostsData } from '../lib/posts'

const inter = Inter({ subsets: ['latin'] })

type Post = {
  id?: string
  title?: string
  date?: string
  content?: string
}

export default function Home({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(posts)

  return (
    <div className={clsx('flex min-h-screen flex-col', inter.className)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container py-10">
        <ul>
          {posts.map(({ id, date, title }) => (
            <li key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>
      </main>
      <footer className="mt-auto flex justify-center gap-3">
        <p>hello</p>
        <p>hello</p>
        <p>hello</p>
        <p>hello</p>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps<{ posts: Post[] }> = async () => {
  const allPostsData: Post[] = getSortedPostsData()
  return {
    props: {
      posts: allPostsData,
    },
  }
}
