import clsx from 'clsx'
import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { getSortedPostsData } from '@/lib/posts'
import { PostType } from '@/lib/types'
import BlogCard from '@/components/BlogCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(posts)

  return (
    <div className={clsx('flex min-h-screen flex-col', inter.className)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container py-10">
        <div className="grid gap-3">
          {posts.map((post) => (
            <div key={post.id}>
              <BlogCard {...post} />
              {post.excerpt && <p className='prose'>{post.excerpt}</p>}
            </div>
          ))}
        </div>
      </main>
      <footer className="mt-auto flex justify-center gap-3">
        <p>hello</p>
        <p>hello</p>
        <p>hello</p>
        <p>hello</p>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps<{
  posts: PostType[]
}> = async () => {
  const allPostsData: PostType[] = getSortedPostsData()
  return {
    props: {
      posts: allPostsData,
    },
  }
}
